baseurl: 'https://fritz.ninja/'
title: Fritz
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
paginate: 20
canonifyurls: true
pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
enableEmoji: true
enableInlineShortcodes: true
disqusShortname: ''
params:
  author: Jan Stevens
  info: Full Stack <img class="emoji-ninja" src="/img/ninja.png"></img> Developer
  description: Jan Stevens's personal website
  keywords: 'blog,developer,fullstack,antwerp,ruby,rails'
  avatarurl: /img/portret.png
  favicon_32: /img/favicon-32x32.png
  favicon_16: /img/favicon-16x16.png
  custom_css:
    - /css/bootstrap-grid.min.css
    - /css/base.css
  hidecredits: false
  hidecopyright: false
  rtl: false
  math: true
  social:
    - name: Github
      icon: fab fa-github fa-2x
      weight: 1
      url: 'https://github.com/JanStevens'
    - name: Stack Overflow
      icon: fab fa-stack-overflow fa-2x
      weight: 2
      url: 'https://stackoverflow.com/users/1226156/danfritz'
    - name: LinkedIn
      icon: fab fa-linkedin fa-2x
      weight: 3
      url: 'https://www.linkedin.com/in/fritzhut/'
menu:
  main:
    - name: About
      weight: 1
      url: /about/
    - name: Experience
      weight: 2
      url: /experience/
